export const projects = [
  {
    id: 1,
    title: "Gebeta SACCOS",
    category: "Full Stack",
    description:
      "Financial services platform for Ethiopia's most trusted SACCOS, serving 10,000+ members with savings, loans, and investment services.",
    images: [
      "images/ProjectsImage/gebeta1.png",
      "images/ProjectsImage/gebeta2.png",
      "images/ProjectsImage/gebeta3.png",
      "images/ProjectsImage/gebeta4.png",
    ],
    tags: ["NextJs", "Node.js", "Supabase", "Financial Services"],
    siteLink: "https://gebeta-saccos.onrender.com/",
    stats: [
      "10,000+ Active Members",
      "50M+ Birr in Loans",
      "15+ Years of Service",
      "98% Customer Satisfaction",
    ],
  },
  {
    id: 2,
    title: "AURA Community",
    category: "FrontEnd",
    description:
      "Mental wellness platform providing support, resources and community for mental health awareness in Ethiopia.",
    images: [
      "images/ProjectsImage/aura1.png",
      "images/ProjectsImage/aura2.png",
      "images/ProjectsImage/aura3.png",
    ],
    tags: ["NextJs", "Mental Health", "Community Support"],
    siteLink: "https://aura-community.onrender.com/",
    stats: [
      "1000+ Community Members",
      "500+ Lives Supported",
      "50+ Support Groups",
      "4.9/5 Rating",
    ],
  },
  {
    id: 4,
    title: "Dirlink-Shipping Connector",
    category: "FrontEnd",
    description:
      "A well-designed shipping connector with admin and customer dashboard.",
    images: [
      "images/ProjectsImage/dirlink_logo1.png",
      "images/ProjectsImage/dirlink_logo2.png",
      "images/ProjectsImage/dirlink_logo3.png",
      "images/ProjectsImage/dirlink_logo4.png",
      "images/ProjectsImage/dirlink_logo5.png",
      "images/ProjectsImage/dirlink_logo6.png",
      "images/ProjectsImage/dirlink_logo7.png",
      "images/ProjectsImage/dirlink_logo8.png",
      "images/ProjectsImage/dirlink_logo9.png",
      "images/ProjectsImage/dirlink_logo10.png",
      "images/ProjectsImage/dirlink_logo11.png",
      "images/ProjectsImage/dirlink_logo12.png",
    ],
    tags: ["React", "Typescript", "Node.js", "Express"],
    siteLink: "https://dirlinksdev.addissystems.et/",
    sourceLink: "https://github.com/hailemichael121",
  },
  {
    id: 5,
    title: "Country Side Village Illustration",
    category: "Others",
    description:
      "A C++ computer graphics project showcasing a countryside village.",
    video: "images/ProjectsImage/CountrySideVilageShowCase.mp4",
    tags: ["C++", "Computer Graphics"],
    sourceLink: "https://github.com/hailemichael121/Country_Side_Village",
  },
  {
    id: 6,
    title: "Hate Speech Detection",
    category: "Machine Learning",
    description: "A custom Telegram bot for hate speech detection.",
    images: ["images/ProjectsImage/HatespeechImage.jpeg"],
    tags: ["Python", "Machine Learning", "Telegram Bot"],
    sourceLink: "https://github.com/hailemichael121/hate_speech_detection",
  },
  {
    id: 7,
    title: "Mezgebe Sbhat",
    category: "Mobile",
    description:
      "An Ethiopian Orthodox Tewahdo learning mobile app for collaboration.",
    images: ["images/ProjectsImage/mezgebeSbhat.png"],
    tags: ["Flutter", "Dart", "Mobile App"],
    sourceLink: "https://github.com/yabulala432/mezgebe_sbhat",
  },
  {
    id: 9,
    title: "Gamehub Demo",
    category: "FrontEnd",
    description: "A demo platform for game downloads.",
    images: [
      "images/ProjectsImage/gamehub1.png",
      "images/ProjectsImage/gamehub2.png",
      "images/ProjectsImage/gamehub3.png",
      "images/ProjectsImage/gamehub4.png",
      "images/ProjectsImage/gamehub5.png",
    ],
    tags: ["React", "Typescript", "Gaming"],
    siteLink: "https://game-hub-psi-three.vercel.app/",
  },
  {
    id: 10,
    title: "Emojitale",
    category: "Others",
    description: "An interactive emoji-based storytelling platform.",
    images: [
      "images/ProjectsImage/emojitale1.png",
      "images/ProjectsImage/emojitale2.png",
      "images/ProjectsImage/emojitale1.png",
    ],
    tags: ["React", "Storytelling", "Emojis"],
    siteLink: "https://emojitale.netlify.app/",
  },
   {
    id: 11,
    title: "ትምህርት ቤት (Timhrt Bet)",
    category: "Full Stack",
    description: "Modern Learning Management System for Ethiopian educational institutions to manage courses, track student progress, and facilitate learning experiences.",
    images: [
      "images/ProjectsImage/timhrt1.png",
      "images/ProjectsImage/timhrt2.png",
      "images/ProjectsImage/timhrt3.png"
    ],
    tags: ["React", "Node.js", "MongoDB", "Education", "LMS"],
    siteLink: "https://timhrtbet-hailemichael121s-projects.vercel.app/",
    features: [
      "Course Management",
      "Student Progress Tracking",
      "Assignment Management",
      "Analytics Dashboard",
      "Plagiarism Detection",
      "Communication Tools"
    ]
  },
];
